//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeForWork.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int ID { get; set; }
        public Nullable<int> StartID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string NameMember { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Position Position { get; set; }
        public virtual Start Start { get; set; }
        public virtual Section Section { get; set; }
    }
}
